server:
  port: 8888
spring:
  application:
    name: demo-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hachibitz/demo-config-server.git
          #username: username
          #password: password
          default-label: main
          search-paths:
          - 'greeting-service*'